Revise system headers / enforce c11 (#1695)
!!! Breaking Change !!!
----
All Sming based applications used to have a user_config.h file inside of the application `include/` directory. If your application user_config.h is the same as the one coming from the Sming then make sure to delete it .

If you don't want to delete it most probably the compilation will break with similar error message:
```
include/user_config.h:26:40: fatal error: espinc/c_types_compatible.h: No such file or directory
  #include <espinc/c_types_compatible.h>
```

Replace ` #include <espinc/c_types_compatible.h>` with `include <c_types.h>` to fix this issue.
-----

This PR includes the following changes:
* Standardise data types
* Use `uint32_t` in preference to `uint32`, etc.
* Arduino libraries use a mixture so still need to maintain definitions for those
* Build `C` files within modules to c11 standard (previously defaulted to `gnu90`)
* Move `espinc\c_types_compatible.h` -> `c_types.h`
* Simplify and tidy Esp8266 system headers
* Rename `espinc/c_types_compatible.h` as `c_types.h`, revise to use `stdint` and `stdbool` definitions
* Place location for `c_types.h` and `mem.h` ahead of SDK version in makefiles
* Move system definitions from `user_config.h` into `esp_systemapi.h` (exclude LWIP)
* Don't #include `user_config.h` from `esp_systemapi.h`
* Move missing memory API definitions out of `esp_systemapi.h` and into `mem.h`
* Simplify other headers
* Fix samples - use <esp_systemapi.h> to ensure correct c_types.h gets used
* Move attribute definitions and macros out of ctypes.h
* Add `WEAK_ATTR` macro to allow selective weak symbol support
* Not a C/C++ standard feature and not consistently applied on all platforms, so avoid where possible.